### ISSUE TITLE
pr-action: Delete stacks for PR testing if the test is successfull

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-solutions/aws-media-insights-content-localization#191]
bucket cleanup proceeds whether the stack is there or not, this can result in dangling CF distributions.  deleting stacks that are not needed for debugging should reduce the liklihood of this happening.

**Comment by ianwow** [comment]
The pr workflow does in fact delete stacks:
https://github.com/aws-solutions/aws-media-insights-content-localization/blob/7ae09898ee4b9247486a4815321d38c7a6d3b86c/.github/workflows/pr-workflow.yml#L321
