### ISSUE TITLE
Analysis view: xx.js:1 Uncaught ReferenceError: url is not defined 

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-solutions/aws-media-insights-content-localization#29]
This in the JavaScript console after swtiching to the Analysis view:

xx.js:1 Uncaught ReferenceError: url is not defined
    at XXProvider.getVideoData (xx.js:1)
    at XXProvider.addVideo (abstract-provider.js:1)
    at HTMLVideoElement.<anonymous> (xx.js:1)
    at Function.each (jquery-3.2.1.min.js:2)
    at r.fn.init.each (jquery-3.2.1.min.js:2)
    at XXProvider.search (xx.js:1)
    at abstract-provider.js:1

**Comment by 2guny** [comment]
I have same error, too... someone help us plz

**Comment by ianwow** [comment]
1. This issue does not appear to affect what's rendered in the UI. 
2. This issue appears to relate to an npm package that is not in our dependency tree (see `npm list`)
3. I haven't been able to reproduce this issue. 

For those reasons, I'm going to close this issue. Please add a comment if you think this issue deserves more attention.

**Comment by jprincon** [comment]
Hello, this problem is related to some extension that has been installed in Chrome. To solve this problem you need to disable the extension which in my case was the download videos extension which affects everything. It's not an npm issue, it's an external issue.
