### ISSUE TITLE
Waveform component initialization is disabled in Analysis.vue and will not be displayed in Audio path components

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-solutions/aws-media-insights-content-localization#37]
There is a problem in getWorkflowId()- asset_id in path is resolving to undefined for some reason.

The Waveform is an audio frequency graph that is shown on audio components in place of the line chart in video operator components.  This graph gives an overview of times in the video when sound is present.  Removing the Waverform component will just leave some blank space below the player on the Audio component pages

**Comment by aburkleaux-amazon** [comment]
Remove waveform component entirely.

**Comment by ianwow** [comment]
this issue is obsolete since the waveform component has been removed.
