### ISSUE TITLE
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-solutions/aws-media-insights-content-localization#47]
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Analysis of this code determined that this line of code contains a resource that might not have closed properly. A resource leak can slow down or crash your system. Programs are strongly recommended to use the built in `with` keyword to open a resource or to use a `try-finally` block to open and close resources explicitly. The [contextlib](https://docs.python.org/3/library/contextlib.html) module provides helpful utilities for using the `with` statement.

[Learn more](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files)

_Originally posted by @aburkleaux-amazon in https://github.com/aws-samples/aws-media-insights-vod-subtitles/pull/44#discussion_r574183922_

**Comment by ianwow** [comment]
not useful.
