### ISSUE TITLE
Epic: as a content owner I want to improve the accuracy of the results from the localization workflow so I can publish my content faster

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-solutions/aws-media-insights-content-localization#54]
# Epic: as a content owner I want to improve the accuracy of the results from the automated localization workflow, so I can publish my content faster and at a lower cost

## Story: As a content owner I want to provide customizations for Amazon Translate and Amazon Transcribe when I run my workflow so that editors and translators spend less time correcting the machine generated localization assets.

I created Custom Vocabularies, Custom Language Models, Custom Terminologies and Parallel Data sets outside the Content Localization application and I want to make use of them when I process my videos.  I can select from existing Custom Vocabularies, Custom Language Models, Custom Terminologies and Parallel Data that are available in my account when I upload content for processing.  The output of the workflow reflects the use of the parallel data.

## Story: As a content owner I want a guided experience that uses the results of corrections made by transcriptionists and translators for creating domain specific customizations for Amazon Translate and Amazon Transcribe so I can easily leverage the results of Human in the Loop corrections to create more accurate results for a set of content.

**Comment by ianwow** [comment]
both #51 and #17 are closed, so I'm closing this.
