### ISSUE TITLE
FIXME: filtering source languge from language tag list doesn't refresh tag picker in UI

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aws-solutions/aws-media-insights-content-localization#55]
https://github.com/aws-samples/aws-media-insights-content-localization/blob/9a489fd6187b16c46948656c40198ebfa76c0aab/src/views/UploadToAWSS3.vue#L472

//FIXME: filtering source languge from language tag list doesn't refresh 
// tag picker in UI.  So, if source language is English to start, English is 
// removed from the translation target languages.  When source language
// is changed to Spanish, Engish is added back to the tags on the Vue 
// Translation component but Engish tag is still missing on the tag
// picker.  For now, leave the source language in the list.
//.filter(x => x.text !== this.sourceLanguageCode)

**Comment by ianwow** [comment]
this has been fixed
